#!/usr/bin/env python3
from lib import Installer, Kafka, Gui, Cron, Kong
      
installer = Installer()
installer.say_wellcome()

kafka = Kafka().ask_persistence_time().ask_persistence_volume().ask_volume_size()
kong = Kong().ask_req_per_minute().ask_req_per_hour().ask_pg_username().ask_pg_password()
cron = Cron().ask_use().ask_replicas()
gui = Gui().ask_use().ask_replicas()

installer.create_vars_file_for([kafka, kong, cron, gui]).call_ansible()

# print("hey there, this is my first pip package")